### ISSUE TITLE
Issues in data_reader.py and train.py

### ISSUE THREAD

**Issue by matteobrv** [1783696285/SKS-master#2]
Hi there,

I tried to run your code and so far I've stumbled upon a couple of issues. I'd really appreciate it if you could help me look into them.

1. there seems to be an indentation error on line 125 in `data_reader.py`;
2. in `train.py`, on line 79, you call `dataset.get_data(args)`, where `dataset` is an alias for `data_reader.py`. Unfortunately, there seems to be no `get_data` implemented in the latter. This yields `AttributeError: module 'data_reader' has no attribute 'get_data'`.
3. at the end of `data_reader.py` you mention two files, `labeled_data.csv`, which I managed to retrieve thanks to the information provided in readme and `new_hate_word.txt`. I'm not quite sure where to look for the latter. Is it by any chance the txt file in `SKS/data/word_list/`?

Any suggestions as to how I could get past issue 2 and 3 would be really helpful.
Thanks

**Comment by 1783696285** [comment]
Thank you for pointing out this issue, I have updated this part of the code. &nbsp;And, if you run into indentation error again, you can modify it by yourself.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1783696285/SKS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 凌晨0:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1783696285/SKS] Indentation and AttributeError in data_reader.py and train.py (Issue #2)





 
Hi there,
 
I tried to run your code and so far I've stumbled upon a couple of issues. I'd really appreciate it if you could help me look into them.
  
there seems to be an indentation error on line 240 in data_reader.py;
 
in train.py, on line 79, you call dataset.get_data(args), where dataset is an alias for data_reader.py. Unfortunately, there seems to be no get_data implemented in the latter. This yields AttributeError: module 'data_reader' has no attribute 'get_data'.
  
Any suggestions as to how I could get past the second issue would be really helpful.
 Thanks
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by matteobrv** [comment]
@1783696285 thank you for taking the time to look into this. Do you think you could push the changes on the `main` branch? Also, do you have any suggestions with respect to the `AttributeError` and the missing `new_hate_word.txt` I was mentioning in my previous message in point 2 and 3, respectively?

Thanks

**Comment by 1783696285** [comment]
I have push it now. Sorry about that!!! 
the new_hate_word.txt was build manually.  You can also collect/expand  them by yourself. The paper gives urls to two main sources.

**Comment by matteobrv** [comment]
@1783696285 thank you for your help. Unfortunately, I'm still unable to run your code as another issue with `data_reader.py` came up. 

If I understand correctly, in `read_dataset` you read both the train and test datasets of semeval 2019 into two dataframes, `df_task` and `df_task_test`. Shortly after, on line 248 and 250, you create `data_all` and `df_task_test` as follows:
```
data_all = df_task[['tweet', 'label', 'task_idx']]
df_task_test = df_task_test[['tweet', 'label', 'task_idx']]
```
This however produces an exception `KeyError: "['tweet', 'label'] not in index"`, as the semeval data-sets contain neither the `tweet` nor the `label` column.

If you had any suggestions as to how to proceed, I'd really appreciate it.

Thanks

**Comment by didiJ-sudo** [comment]
> @1783696285 thank you for your help. Unfortunately, I'm still unable to run your code as another issue with `data_reader.py` came up.
> 
> If I understand correctly, in `read_dataset` you read both the train and test datasets of semeval 2019 into two dataframes, `df_task` and `df_task_test`. Shortly after, on line 248 and 250, you create `data_all` and `df_task_test` as follows:
> 
> ```
> data_all = df_task[['tweet', 'label', 'task_idx']]
> df_task_test = df_task_test[['tweet', 'label', 'task_idx']]
> ```
> 
> This however produces an exception `KeyError: "['tweet', 'label'] not in index"`, as the semeval data-sets contain neither the `tweet` nor the `label` column.
> 
> If you had any suggestions as to how to proceed, I'd really appreciate it.
> 
> Thanks

我也遇到了同样的问题，请问你解决了吗

**Comment by matteobrv** [comment]
> 我也遇到了同样的问题，请问你解决了吗

Hi @didiJ-sudo,

I somehow managed to circumvent this issue by changing the column names in the data sets directly.
For the **SemEval** data sets I changed the columns as follows:

| original name | new name |
|--------------------|---------------|
| **`id`**                  | **`task_idx`** |
| **`text`**               | **`tweet`**      |
| **`HS`**                | **`label`**       |
| `TR`                | `TR`          |
| `AG`                | `AG`         |

For the **Davidson** (DV) data sets I changed the columns as follows:

| original name | new name |
|--------------------|---------------|
| `count`                  | `count` |
| `hate_speech`               | `hate_speech`      |
| `offensive_language`                | `offensive_language`       |
| `neither`                | `neither`          |
| **`class`**                | **`label`**         |
| `tweet`                | `tweet`         |

For the sentiment data set from Kaggle I didn't change anything.

I hope this is going to help

**Comment by didiJ-sudo** [comment]
> > 我也遇到了同样的问题，请问你解决了吗
> 
> Hi @didiJ-sudo,
> 
> I somehow managed to circumvent this issue by changing the column names in the data sets directly. For the **SemEval** data sets I changed the columns as follows:
> 
> original name	new name
> **`id`**	**`task_idx`**
> **`text`**	**`tweet`**
> **`HS`**	**`label`**
> `TR`	`TR`
> `AG`	`AG`
> For the **Davidson** (DV) data sets I changed the columns as follows:
> 
> original name	new name
> `count`	`count`
> `hate_speech`	`hate_speech`
> `offensive_language`	`offensive_language`
> `neither`	`neither`
> **`class`**	**`label`**
> `tweet`	`tweet`
> For the sentiment data set from Kaggle I didn't change anything.
> 
> I hope this is going to help

还想请教一下您是否对mylayers.py进行了修改呢？运行中报了许多错还没有调试出来T_T

**Comment by didiJ-sudo** [comment]
> > 我也遇到了同样的问题，请问你解决了吗
> 
> Hi @didiJ-sudo,
> 
> I somehow managed to circumvent this issue by changing the column names in the data sets directly. For the **SemEval** data sets I changed the columns as follows:
> 
> original name	new name
> **`id`**	**`task_idx`**
> **`text`**	**`tweet`**
> **`HS`**	**`label`**
> `TR`	`TR`
> `AG`	`AG`
> For the **Davidson** (DV) data sets I changed the columns as follows:
> 
> original name	new name
> `count`	`count`
> `hate_speech`	`hate_speech`
> `offensive_language`	`offensive_language`
> `neither`	`neither`
> **`class`**	**`label`**
> `tweet`	`tweet`
> For the sentiment data set from Kaggle I didn't change anything.
> 
> I hope this is going to help

Hi @matteobrv
还想请教一下对于DV数据集是使用什么作为测试集呢？

**Comment by matteobrv** [comment]
> 还想请教一下对于DV数据集是使用什么作为测试集呢？

Hi @didiJ-sudo,

according to the [original paper](https://aclanthology.org/2021.acl-long.556.pdf) (section 4.2 Training Details), for the DV data set, the authors used a 5-fold cross-validation approach. So I wrote a very basic script, relying on [Scikit Learn](https://scikit-learn.org/stable/modules/cross_validation.html) to treat the data set accordingly.
