### ISSUE TITLE
Ablating Category Embeddings

### ISSUE THREAD

**Issue by matteobrv** [1783696285/SKS-master#3]
Hi there @1783696285,

I'm trying to reproduce the results reported in Table 3 of your paper. Specifically, those where both sentiment knowledge and category embeddings are ablated `-sc`.
I managed to successfully run your model ablating sentiment knowledge alone `-s`, but I'm struggling to understand how to ablate category embeddings. Do you have any pointers as to how I should go about it?

Thanks

**Comment by 1783696285** [comment]
You just need to change the embedding layer, the multi-head attention(4*100—>3*100) and Dense(400—>300).

**Comment by 1783696285** [comment]
You just need to change the embedding layer, the multi-head attention(4*100—>3*100) and Dense(400—>300).

**Comment by 1783696285** [comment]
You just need to change the embedding layer, the multi-head attention(4x100—>3x100) and Dense(400—>300).

**Comment by didiJ-sudo** [comment]
> Hi there @1783696285,
> 
> I'm trying to reproduce the results reported in Table 3 of your paper. Specifically, those where both sentiment knowledge and category embeddings are ablated `-sc`. I managed to successfully run your model ablating sentiment knowledge alone `-s`, but I'm struggling to understand how to ablate category embeddings. Do you have any pointers as to how I should go about it?
> 
> Thanks

Hi, 请问您可以正常运行这个项目吗？代码运行环境是什么呢？我在运行过程中遇到了很多莫名其妙的问题。目前还无法正常运行T-T
Thanks
