### ISSUE TITLE
issues on mylayers.py

### ISSUE THREAD

**Issue by didiJ-sudo** [1783696285/SKS-master#4]
Hi there,

我想请教一下仓库中mylayers.py是代码的最终版本吗，在运行中一直在报这个文件的错误，不知该如何修改。T_T不胜感激

Thanks

**Comment by 1783696285** [comment]
I have reviewed my code and fixed some issues. You can use the new code.

**Comment by didiJ-sudo** [comment]
> I have reviewed my code and fixed some issues. You can use the new code.

Thanks!!!!!!!

**Comment by didiJ-sudo** [comment]
> I have reviewed my code and fixed some issues. You can use the new code.

我运行了代码，在SE数据集上Acc仅有59，F1仅有60，（论文中分别为65.9和65.2）不知道是因为什么T-T。

**Comment by DuTim** [comment]
> > I have reviewed my code and fixed some issues. You can use the new code.
> 
> 我运行了代码，在SE数据集上Acc仅有59，F1仅有60，（论文中分别为65.9和65.2）不知道是因为什么T-T。

你现在能复现出paper中的结果吗
